### ISSUE TITLE
Cannot read properties of null (reading 'maxCrawledPlaces')

### ISSUE THREAD

**Issue by FilipCichorek** [apify-projects/store-crawler-google-places#307]
Hi.
I installed apify globally, copied the repo, did npm install and then apify run and I get this error:

For my comfort, I replaced the original path with "catalog"

```
Run: npm start

> crawler-google-places@1.0.0 start
> node ./src/main.js

INFO  System info {"apifyVersion":"2.3.2","apifyClientVersion":"2.6.0","osType":"Linux","nodeVersion":"v16.17.1"}
ERROR 
  TypeError: Cannot read properties of null (reading 'maxCrawledPlaces')
      at module.exports.makeInputBackwardsCompatible (/Catalog/Apify/crawler-google-places/src/utils/input-validation.js:19:15)
      at /Catalog/Apify/crawler-google-places/src/main.js:27:5
      at async run (/Catalog/Apify/crawler-google-places/node_modules/apify/build/actor.js:182:13)
Error: npm exited with code 91
```

**Comment by FilipCichorek** [comment]
I'm a retard, i dont know why i didn't find it early: https://github.com/drobnikj/crawler-google-places/issues/239. Im sorry.
